"""Chain-of-custody audit logging, evidence path guard, and tool-call counter."""
import json
import uuid
import hashlib
import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# Top-level directory names that are read-only evidence on SIFT Workstation.
_EVIDENCE_TOP_DIRS = {"cases", "mnt", "media"}

# Module-level tracker for the most recently generated audit_id.
# Used by tool wrappers to embed the id in their JSON response without
# changing every _run() function signature.
_last_audit_id: str = ""


def guard_output_path(path: str) -> str:
    """
    Verify a planned output path does NOT resolve into evidence directories.

    Raises PermissionError if the path resolves under /cases/, /mnt/, or /media/.
    Uses Path.parts for cross-platform correctness (Linux and Windows).
    """
    resolved = Path(path).resolve()
    parts = resolved.parts
    if len(parts) >= 2 and parts[1] in _EVIDENCE_TOP_DIRS:
        raise PermissionError(
            f"Writing to evidence path is forbidden (architectural safety enforcement): "
            f"{path!r} resolves to {str(resolved)!r}. "
            "Evidence directories (/cases/, /mnt/, /media/) are strictly read-only."
        )
    return str(resolved)


# Binaries that can destroy, exfiltrate, or alter evidence/state. The MCP server
# must NEVER run these — enforced here in code, not via LLM prompt instructions.
_FORBIDDEN_BINARIES = {
    "rm", "rmdir", "del", "dd", "shred", "mkfs", "fdisk", "parted", "wipefs",
    "format", "mv", "cp", "chmod", "chown", "truncate", "tee", "ln",
    "wget", "curl", "scp", "sftp", "ssh", "nc", "ncat", "netcat", "telnet",
    "ftp", "rsync", "bash", "sh", "zsh", "powershell", "pwsh", "cmd",
    "kill", "pkill", "mount", "umount",
    "useradd", "passwd", "iptables", "systemctl", "crontab", "at",
}
# Write-redirection / shell-chaining tokens that could smuggle a destructive op.
_FORBIDDEN_TOKENS = {">", ">>", "|", ";", "&&", "||", "`", "$(", "&"}


def guard_command(cmd) -> None:
    """Reject any command that invokes a destructive/exfiltration binary or uses
    shell redirection/chaining. Raises PermissionError. Architectural enforcement —
    every tool execution path routes through this before subprocess.run().

    Accepts a command as a list (argv) — the only form tools use. The basename of
    argv[0] is checked against the forbidden set; dotnet/vol/EZ tool .dll launches
    pass. Tokens are checked across all args.
    """
    if isinstance(cmd, str):
        raise PermissionError(
            "Shell-string commands are forbidden; use an argv list (no shell)."
        )
    if not cmd:
        return
    exe = Path(str(cmd[0])).name.lower()
    if exe.endswith(".exe"):
        exe = exe[:-4]
    if exe in _FORBIDDEN_BINARIES:
        raise PermissionError(
            f"Refusing to execute forbidden binary {exe!r} (architectural safety "
            f"enforcement). The DeepSIFT MCP server cannot run destructive, "
            f"exfiltration, or arbitrary-code commands."
        )
    for arg in cmd:
        s = str(arg)
        if s in _FORBIDDEN_TOKENS or any(tok in s for tok in (">", "|", ";", "`", "$(")):
            raise PermissionError(
                f"Refusing command with shell redirection/chaining token in {s!r} "
                f"(architectural safety enforcement)."
            )


def _get_dirs():
    from mcp_server.config import EXPORTS_DIR, ANALYSIS_DIR
    return EXPORTS_DIR, ANALYSIS_DIR


# ── Audit ID ──────────────────────────────────────────────────────────────────

def get_last_audit_id() -> str:
    """Return the audit_id generated by the most recent log_tool_execution call."""
    return _last_audit_id


# ── Tool-call counter ─────────────────────────────────────────────────────────

def _counter_path() -> Path:
    _, analysis_dir = _get_dirs()
    return analysis_dir / "tool_call_counter.json"


def increment_tool_counter() -> int:
    """Increment per-session call counter. Returns new count."""
    path = _counter_path()
    try:
        count = json.loads(path.read_text(encoding="utf-8")).get("count", 0) + 1
    except Exception:
        count = 1
    try:
        path.write_text(json.dumps({"count": count}), encoding="utf-8")
    except Exception:
        pass
    return count


def get_tool_count() -> int:
    """Return current tool-call count for this session."""
    try:
        return json.loads(_counter_path().read_text(encoding="utf-8")).get("count", 0)
    except Exception:
        return 0


def reset_tool_counter() -> None:
    """Reset counter to zero (called by finish_analysis)."""
    try:
        _counter_path().write_text(json.dumps({"count": 0}), encoding="utf-8")
    except Exception:
        pass


# ── Main audit logger ─────────────────────────────────────────────────────────

def log_tool_execution(
    tool_name: str,
    command: list,
    raw_output: str,
    result_summary: str = "",
    error: str = "",
) -> dict:
    """
    Write one audit entry per tool call. Saves raw output to exports/ and appends
    a JSON line to forensic_audit.log.

    Returns the entry dict (including audit_id) so callers can embed it in responses.
    """
    global _last_audit_id

    exports_dir, analysis_dir = _get_dirs()
    timestamp = datetime.now(timezone.utc).isoformat()
    safe_ts = timestamp.replace(":", "-").replace(".", "-")
    output_hash = hashlib.sha256(raw_output.encode()).hexdigest()

    # Human-readable unique ID: dsift-<date>-<8hex>
    audit_id = f"dsift-{safe_ts[:10]}-{uuid.uuid4().hex[:8]}"
    _last_audit_id = audit_id

    export_file = exports_dir / f"{tool_name}_{safe_ts}.txt"
    try:
        guard_output_path(str(export_file))
    except PermissionError as e:
        logger.error(f"Audit log refused to write to evidence path: {e}")
        raise
    export_file.write_text(raw_output, encoding="utf-8")

    entry = {
        "audit_id": audit_id,
        "timestamp": timestamp,
        "tool": tool_name,
        "command": " ".join(str(c) for c in command),
        "raw_output_sha256": output_hash,
        "raw_output_file": str(export_file),
        "result_summary": result_summary,
        "error": error,
    }

    audit_log = analysis_dir / "forensic_audit.log"
    with open(audit_log, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")

    return entry
