"""Chain-of-custody audit logging, evidence path guard, and tool-call counter."""
import json
import os
import uuid
import hashlib
import hmac
import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# Top-level directory names that are read-only evidence on SIFT Workstation.
_EVIDENCE_TOP_DIRS = {"cases", "mnt", "media"}

# Module-level tracker for the most recently generated audit_id.
# Used by tool wrappers to embed the id in their JSON response without
# changing every _run() function signature.
_last_audit_id: str = ""


def guard_output_path(path: str) -> str:
    """
    Verify a planned output path does NOT resolve into evidence directories.

    Raises PermissionError if the path resolves under /cases/, /mnt/, or /media/.
    Uses Path.parts for cross-platform correctness (Linux and Windows).
    """
    resolved = Path(path).resolve()
    parts = resolved.parts
    if len(parts) >= 2 and parts[1] in _EVIDENCE_TOP_DIRS:
        raise PermissionError(
            f"Writing to evidence path is forbidden (architectural safety enforcement): "
            f"{path!r} resolves to {str(resolved)!r}. "
            "Evidence directories (/cases/, /mnt/, /media/) are strictly read-only."
        )
    return str(resolved)


# Binaries that can destroy, exfiltrate, or alter evidence/state. The MCP server
# must NEVER run these — enforced here in code, not via LLM prompt instructions.
_FORBIDDEN_BINARIES = {
    "rm", "rmdir", "del", "dd", "shred", "mkfs", "fdisk", "parted", "wipefs",
    "format", "mv", "cp", "chmod", "chown", "truncate", "tee", "ln",
    "wget", "curl", "scp", "sftp", "ssh", "nc", "ncat", "netcat", "telnet",
    "ftp", "rsync", "bash", "sh", "zsh", "powershell", "pwsh", "cmd",
    "kill", "pkill", "mount", "umount",
    "useradd", "passwd", "iptables", "systemctl", "crontab", "at",
}
# Write-redirection / shell-chaining tokens that could smuggle a destructive op.
_FORBIDDEN_TOKENS = {">", ">>", "|", ";", "&&", "||", "`", "$(", "&"}


def guard_command(cmd) -> None:
    """Reject any command that invokes a destructive/exfiltration binary or uses
    shell redirection/chaining. Raises PermissionError. Architectural enforcement —
    every tool execution path routes through this before subprocess.run().

    Accepts a command as a list (argv) — the only form tools use. The basename of
    argv[0] is checked against the forbidden set; dotnet/vol/EZ tool .dll launches
    pass. Tokens are checked across all args.
    """
    if isinstance(cmd, str):
        raise PermissionError(
            "Shell-string commands are forbidden; use an argv list (no shell)."
        )
    if not cmd:
        return
    exe = Path(str(cmd[0])).name.lower()
    if exe.endswith(".exe"):
        exe = exe[:-4]
    if exe in _FORBIDDEN_BINARIES:
        raise PermissionError(
            f"Refusing to execute forbidden binary {exe!r} (architectural safety "
            f"enforcement). The DeepSIFT MCP server cannot run destructive, "
            f"exfiltration, or arbitrary-code commands."
        )
    for arg in cmd:
        s = str(arg)
        if s in _FORBIDDEN_TOKENS or any(tok in s for tok in (">", "|", ";", "`", "$(")):
            raise PermissionError(
                f"Refusing command with shell redirection/chaining token in {s!r} "
                f"(architectural safety enforcement)."
            )


def _get_dirs():
    from mcp_server.config import EXPORTS_DIR, ANALYSIS_DIR
    return EXPORTS_DIR, ANALYSIS_DIR


# ── Audit ID ──────────────────────────────────────────────────────────────────

def get_last_audit_id() -> str:
    """Return the audit_id generated by the most recent log_tool_execution call."""
    return _last_audit_id


# ── Tool-call counter ─────────────────────────────────────────────────────────

def _counter_path() -> Path:
    _, analysis_dir = _get_dirs()
    return analysis_dir / "tool_call_counter.json"


def increment_tool_counter() -> int:
    """Increment per-session call counter. Returns new count."""
    path = _counter_path()
    try:
        count = json.loads(path.read_text(encoding="utf-8")).get("count", 0) + 1
    except Exception:
        count = 1
    try:
        path.write_text(json.dumps({"count": count}), encoding="utf-8")
    except Exception:
        pass
    return count


def get_tool_count() -> int:
    """Return current tool-call count for this session."""
    try:
        return json.loads(_counter_path().read_text(encoding="utf-8")).get("count", 0)
    except Exception:
        return 0


def reset_tool_counter() -> None:
    """Reset counter to zero (called by finish_analysis)."""
    try:
        _counter_path().write_text(json.dumps({"count": 0}), encoding="utf-8")
    except Exception:
        pass


# ── Main audit logger ─────────────────────────────────────────────────────────

def log_tool_execution(
    tool_name: str,
    command: list,
    raw_output: str,
    result_summary: str = "",
    error: str = "",
) -> dict:
    """
    Write one audit entry per tool call. Saves raw output to exports/ and appends
    a JSON line to forensic_audit.log.

    Returns the entry dict (including audit_id) so callers can embed it in responses.
    """
    global _last_audit_id

    exports_dir, analysis_dir = _get_dirs()
    timestamp = datetime.now(timezone.utc).isoformat()
    safe_ts = timestamp.replace(":", "-").replace(".", "-")
    output_hash = hashlib.sha256(raw_output.encode()).hexdigest()

    # Human-readable unique ID: dsift-<date>-<8hex>
    audit_id = f"dsift-{safe_ts[:10]}-{uuid.uuid4().hex[:8]}"
    _last_audit_id = audit_id

    export_file = exports_dir / f"{tool_name}_{safe_ts}.txt"
    try:
        guard_output_path(str(export_file))
    except PermissionError as e:
        logger.error(f"Audit log refused to write to evidence path: {e}")
        raise
    export_file.write_text(raw_output, encoding="utf-8")

    entry = {
        "audit_id": audit_id,
        "timestamp": timestamp,
        "tool": tool_name,
        "command": " ".join(str(c) for c in command),
        "raw_output_sha256": output_hash,
        "raw_output_file": str(export_file),
        "result_summary": result_summary,
        "error": error,
    }

    # Tamper-evident hash chain: each entry binds to the hash of the previous one,
    # so altering or deleting any past entry breaks the chain (verify_audit_chain()).
    prev_hash = _read_chain_head(analysis_dir)
    entry["prev_hash"] = prev_hash
    entry["entry_hash"] = _entry_hash(prev_hash, entry)
    _write_chain_head(analysis_dir, entry["entry_hash"])

    # Optional HMAC signing: with an externally-held secret key (DEEPSIFT_AUDIT_KEY),
    # the chain becomes forgery-resistant — an attacker who rewrites the log cannot
    # recompute valid signatures without the key. Without a key, the SHA-256 chain
    # above still detects naive modification/insertion/deletion.
    key = _audit_key()
    if key:
        prev_hmac = _read_hmac_head(analysis_dir)
        entry["prev_hmac"] = prev_hmac
        entry["entry_hmac"] = _entry_hmac(key, prev_hmac, entry["entry_hash"])
        _write_hmac_head(analysis_dir, entry["entry_hmac"])

    audit_log = analysis_dir / "forensic_audit.log"
    with open(audit_log, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")

    return entry


# ── Tamper-evident hash chain ───────────────────────────────────────────────────

_GENESIS = "0" * 64


def _entry_hash(prev_hash: str, entry: dict) -> str:
    """SHA-256 over (prev_hash + canonical entry without its own chain fields)."""
    core = {k: entry[k] for k in (
        "audit_id", "timestamp", "tool", "command", "raw_output_sha256",
        "raw_output_file", "result_summary", "error") if k in entry}
    payload = prev_hash + json.dumps(core, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode()).hexdigest()


def _audit_key() -> bytes | None:
    """Externally-held HMAC secret for forgery-resistant audit signing.

    Read from DEEPSIFT_AUDIT_KEY at call time (so tests/operators can set it per run).
    Returns None when unset — the SHA-256 hash chain still provides tamper *detection*;
    the key adds tamper *resistance* (signatures can't be forged without it).
    """
    k = os.getenv("DEEPSIFT_AUDIT_KEY", "")
    return k.encode("utf-8") if k else None


def _entry_hmac(key: bytes, prev_hmac: str, entry_hash: str) -> str:
    """HMAC-SHA256 chaining over (prev_hmac + this entry's hash)."""
    return hmac.new(key, (prev_hmac + entry_hash).encode("utf-8"), hashlib.sha256).hexdigest()


def _hmac_head_file(analysis_dir):
    return analysis_dir / ".audit_hmac_head"


def _read_hmac_head(analysis_dir) -> str:
    try:
        return _hmac_head_file(analysis_dir).read_text().strip() or _GENESIS
    except Exception:
        return _GENESIS


def _write_hmac_head(analysis_dir, head: str) -> None:
    try:
        _hmac_head_file(analysis_dir).write_text(head)
    except Exception:
        pass


def _chain_head_file(analysis_dir):
    return analysis_dir / ".audit_chain_head"


def _read_chain_head(analysis_dir) -> str:
    f = _chain_head_file(analysis_dir)
    try:
        return f.read_text().strip() or _GENESIS
    except Exception:
        return _GENESIS


def _write_chain_head(analysis_dir, head: str) -> None:
    try:
        _chain_head_file(analysis_dir).write_text(head)
    except Exception:
        pass


def begin_case_audit() -> None:
    """Start a fresh, self-consistent audit chain for a new investigation.

    Archives any existing forensic_audit.log (so prior runs are preserved, not lost)
    and resets the chain head to genesis. Call at the start of an investigation so the
    case's chain of custody verifies cleanly end to end.
    """
    _, analysis_dir = _get_dirs()
    Path(analysis_dir).mkdir(parents=True, exist_ok=True)
    log = analysis_dir / "forensic_audit.log"
    if log.exists() and log.stat().st_size > 0:
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        try:
            log.rename(analysis_dir / f"forensic_audit.{ts}.log.bak")
        except Exception:
            pass
    for head in (_chain_head_file(analysis_dir), _hmac_head_file(analysis_dir)):
        try:
            if head.exists():
                head.unlink()
        except Exception:
            pass


def verify_audit_chain(audit_log_path: str = "") -> dict:
    """Recompute the hash chain over forensic_audit.log and report integrity.

    Returns {"ok": bool, "entries": n, "broken_at": idx|None, "head": hash,
             "hmac_signed": bool, "hmac_ok": bool|None}.
    A broken link means an entry was modified, inserted, or deleted after logging.
    When DEEPSIFT_AUDIT_KEY is set AND the entries carry entry_hmac, the HMAC chain is
    additionally verified (forgery-resistant): hmac_ok is True/False; otherwise None.
    """
    _, analysis_dir = _get_dirs()
    path = Path(audit_log_path) if audit_log_path else analysis_dir / "forensic_audit.log"
    if not path.exists():
        return {"ok": True, "entries": 0, "broken_at": None, "head": _GENESIS,
                "hmac_signed": False, "hmac_ok": None}
    key = _audit_key()
    prev = _GENESIS
    prev_hmac = _GENESIS
    n = 0
    saw_hmac = False
    hmac_ok = None
    with open(path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            n += 1
            try:
                e = json.loads(line)
            except Exception:
                return {"ok": False, "entries": n, "broken_at": i, "head": prev,
                        "reason": "unparseable entry", "hmac_signed": saw_hmac, "hmac_ok": hmac_ok}
            # Back-compat: entries written before chaining have no chain fields.
            if "entry_hash" not in e:
                continue
            expect = _entry_hash(e.get("prev_hash", _GENESIS), e)
            if e.get("prev_hash") != prev and prev != _GENESIS:
                return {"ok": False, "entries": n, "broken_at": i, "head": prev,
                        "reason": "prev_hash mismatch (entry inserted/deleted)",
                        "hmac_signed": saw_hmac, "hmac_ok": hmac_ok}
            if expect != e.get("entry_hash"):
                return {"ok": False, "entries": n, "broken_at": i, "head": prev,
                        "reason": "entry_hash mismatch (entry modified)",
                        "hmac_signed": saw_hmac, "hmac_ok": hmac_ok}
            # HMAC verification (only when signed entries exist and we hold the key).
            if "entry_hmac" in e:
                saw_hmac = True
                if key is not None:
                    want = _entry_hmac(key, e.get("prev_hmac", _GENESIS), e["entry_hash"])
                    if not hmac.compare_digest(want, e["entry_hmac"]):
                        return {"ok": False, "entries": n, "broken_at": i, "head": prev,
                                "reason": "entry_hmac mismatch (forged/modified without key)",
                                "hmac_signed": True, "hmac_ok": False}
                    hmac_ok = True
                    prev_hmac = e["entry_hmac"]
    return {"ok": True, "entries": n, "broken_at": None, "head": prev,
            "hmac_signed": saw_hmac, "hmac_ok": hmac_ok}
